[package]
name = "wms"
version = "0.1.0"
authors = ["duxet <duxetlg@gmail.com>"]

[dependencies]
futures = "0.1"
geo = "0.4"
hyper = "0.11"
serde = "1.0"
serde_derive = "1.0"
tokio-core = "0.1"
url = "1.5"
